version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./MDSpecialist.db
      - CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      - db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=MDSpecialist
      - POSTGRES_USER=concierge_user
      - POSTGRES_PASSWORD=concierge_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - postgres

volumes:
  backend_data:
  postgres_data:
