import React, { useState, useEffect } from 'react';
import { MessageSquare, ChevronDown, ChevronUp, Search } from 'lucide-react';
import { 
  HealthgradesReview, 
  searchReviewsByKeywords, 
  getSearchReviewCount,
  getReviewCount 
} from '../services/api';

interface ProviderReviewsProps {
  npi: string | number;
  searchQuery?: string;  // Pre-generated search query from backend (same as PubMed)
}

export default function ProviderReviews({ npi, searchQuery }: ProviderReviewsProps) {
  const [reviews, setReviews] = useState<HealthgradesReview[]>([]);
  const [totalCount, setTotalCount] = useState<number>(0);
  const [matchingCount, setMatchingCount] = useState<number>(0);
  const [loading, setLoading] = useState(true);
  const [showAll, setShowAll] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const [viewMode, setViewMode] = useState<'relevant' | 'all'>('relevant');

  const PREVIEW_COUNT = 2; // Show 2 reviews by default

  // Use the same search query generated by backend for PubMed search
  // This ensures consistency across reviews and PubMed article filtering
  const keywords = React.useMemo(() => {
    if (searchQuery) {
      console.log(`🔑 [ProviderReviews] Using backend search query for NPI ${npi}: ${searchQuery}`);
    }
    return searchQuery;
  }, [searchQuery, npi]);

  useEffect(() => {
    const fetchReviewData = async () => {
      setLoading(true);
      try {
        if (viewMode === 'relevant' && keywords) {
          // Fetch keyword-filtered reviews
          console.log(`🔍 [ProviderReviews] Fetching relevant reviews for NPI ${npi} with keywords: ${keywords}`);
          const [reviewsData, matchCount, allCount] = await Promise.all([
            searchReviewsByKeywords(npi, keywords, showAll ? 100 : PREVIEW_COUNT),
            getSearchReviewCount(npi, keywords),
            getReviewCount(npi)
          ]);
          console.log(`✅ [ProviderReviews] Found ${matchCount}/${allCount} relevant reviews for NPI ${npi}`);
          setReviews(reviewsData);
          setMatchingCount(matchCount);
          setTotalCount(allCount);
        } else {
          // Fetch all reviews (no filtering)
          console.log(`📋 [ProviderReviews] Fetching all reviews for NPI ${npi}`);
          const [reviewsData, allCount] = await Promise.all([
            searchReviewsByKeywords(npi, undefined, showAll ? 100 : PREVIEW_COUNT),
            getReviewCount(npi)
          ]);
          console.log(`✅ [ProviderReviews] Found ${allCount} total reviews for NPI ${npi}`);
          setReviews(reviewsData);
          setMatchingCount(allCount);
          setTotalCount(allCount);
        }
      } catch (error) {
        console.error(`❌ [ProviderReviews] Error loading reviews for NPI ${npi}:`, error);
        // Set empty state on error to avoid infinite loading
        setReviews([]);
        setMatchingCount(0);
        setTotalCount(0);
      } finally {
        setLoading(false);
      }
    };

    fetchReviewData();
  }, [npi, showAll, viewMode, keywords]);

  if (loading) {
    return (
      <div className="mt-4 p-4 bg-gray-50 rounded-lg">
        <div className="flex items-center gap-2 text-gray-600">
          <MessageSquare className="w-5 h-5" />
          <span>Loading reviews...</span>
        </div>
      </div>
    );
  }

  if (totalCount === 0) {
    return null; // Don't show section if no reviews
  }

  // If no keywords, always show all reviews
  const hasKeywords = keywords !== undefined;
  const displayedReviews = showAll ? reviews : reviews.slice(0, PREVIEW_COUNT);
  const currentCount = viewMode === 'relevant' ? matchingCount : totalCount;

  return (
    <div className="mt-4 border-t pt-4">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between text-left hover:bg-gray-50 p-2 rounded transition-colors"
      >
        <div className="flex items-center gap-2">
          <MessageSquare className="w-5 h-5 text-blue-600" />
          <h3 className="font-semibold text-gray-900">
            Patient Reviews ({totalCount})
            {hasKeywords && viewMode === 'relevant' && matchingCount < totalCount && (
              <span className="text-sm font-normal text-blue-600 ml-2">
                ({matchingCount} relevant)
              </span>
            )}
          </h3>
        </div>
        {expanded ? (
          <ChevronUp className="w-5 h-5 text-gray-400" />
        ) : (
          <ChevronDown className="w-5 h-5 text-gray-400" />
        )}
      </button>

      {expanded && (
        <div className="mt-3 space-y-3">
          {/* Mode Toggle (only show if we have keywords and relevant reviews exist) */}
          {hasKeywords && matchingCount > 0 && (
            <div className="flex gap-2 mb-3">
              <button
                onClick={() => {
                  setViewMode('relevant');
                  setShowAll(false);
                }}
                className={`px-3 py-1.5 text-sm rounded-lg transition-colors flex items-center gap-1 ${
                  viewMode === 'relevant'
                    ? 'bg-blue-600 text-white'
                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                }`}
              >
                <Search className="w-4 h-4" />
                Relevant ({matchingCount})
              </button>
              <button
                onClick={() => {
                  setViewMode('all');
                  setShowAll(false);
                }}
                className={`px-3 py-1.5 text-sm rounded-lg transition-colors ${
                  viewMode === 'all'
                    ? 'bg-blue-600 text-white'
                    : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                }`}
              >
                All Reviews ({totalCount})
              </button>
            </div>
          )}

          {/* No relevant reviews message */}
          {hasKeywords && viewMode === 'relevant' && matchingCount === 0 && (
            <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
              <p className="text-sm text-yellow-800">
                No reviews found matching your condition. 
                <button
                  onClick={() => setViewMode('all')}
                  className="ml-1 underline font-medium hover:text-yellow-900"
                >
                  View all {totalCount} reviews
                </button>
              </p>
            </div>
          )}

          {/* Display reviews */}
          {displayedReviews.map((review) => (
            <div
              key={review.id}
              className="bg-gray-50 rounded-lg p-4 border border-gray-200"
            >
              <div className="flex items-start justify-between mb-2">
                <div className="flex-1">
                  {review.review_author && (
                    <p className="text-sm font-medium text-gray-700">
                      {review.review_author}
                    </p>
                  )}
                  {review.review_date && (
                    <p className="text-xs text-gray-500">{review.review_date}</p>
                  )}
                </div>
              </div>
              
              <p className="text-sm text-gray-700 leading-relaxed">
                {review.review_text}
              </p>
            </div>
          ))}

          {/* Show More/Less Button */}
          {currentCount > PREVIEW_COUNT && (
            <button
              onClick={() => setShowAll(!showAll)}
              className="w-full py-2 px-4 text-sm text-blue-600 hover:text-blue-700 hover:bg-blue-50 rounded-lg transition-colors font-medium"
            >
              {showAll
                ? `Show Less`
                : `Show ${currentCount > 100 ? 'More' : `All ${currentCount}`} Reviews`}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
